-- MySQL Script generated by MySQL Workbench
-- Mon May 25 15:53:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sertaoflix
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sertaoflix` ;

-- -----------------------------------------------------
-- Schema sertaoflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sertaoflix` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sertaoflix` ;

-- -----------------------------------------------------
-- Table `sertaoflix`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`Endereço` (
  `id_Endereço` INT NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `cinema_id_Cinema` INT NOT NULL,
  PRIMARY KEY (`id_Endereço`),
  INDEX `fk_Endereço_cinema1_idx` (`cinema_id_Cinema` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_cinema1`
    FOREIGN KEY (`cinema_id_Cinema`)
    REFERENCES `sertaoflix`.`cinema` (`id_Cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sertaoflix`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `Telefone` VARCHAR(11) NULL,
  `id_Cliente` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_cliente1_idx` (`id_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_cliente1`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `sertaoflix`.`cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sertaoflix`.`avalia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`avalia` (
  `id_Avalia` INT NOT NULL,
  `Nota` DECIMAL(10,1) NOT NULL,
  `Comentario` VARCHAR(500) NULL,
  `cliente_id_Cliente` INT NOT NULL,
  PRIMARY KEY (`id_Avalia`),
  INDEX `fk_Avalia_cliente1_idx` (`cliente_id_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Avalia_cliente`
    FOREIGN KEY (`cliente_id_Cliente`)
    REFERENCES `sertaoflix`.`cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sertaoflix`.`cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`cinema` (
  `id_Cinema` INT NOT NULL,
  `Nome` VARCHAR(80) NULL DEFAULT NULL,
  `CNPJ` VARCHAR(14) NULL DEFAULT NULL,
  `Telefone` VARCHAR(11) NULL DEFAULT NULL,
  `Endereco` VARCHAR(80) NULL DEFAULT NULL,
  `Qnt_salas` INT NULL DEFAULT NULL,
  `Capacidade_total` INT NULL DEFAULT NULL,
  `Acessibilidade_PCD` TINYINT NULL DEFAULT NULL,
  `VIP` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cinema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NULL DEFAULT NULL,
  `Nascimento` DATE NULL DEFAULT NULL,
  `Nivel_fidelidade` ENUM('Bronze', 'Prata', 'Ouro') NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Data_Virou_Prata` DATETIME NULL DEFAULT NULL,
  `Saldo` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_Cliente`),
  UNIQUE INDEX `id_Pessoa_UNIQUE` (`id_Cliente` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`elenco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`elenco` (
  `id_Elenco` INT NOT NULL,
  `Nome` VARCHAR(150) NULL,
  `Nascimento` DATE NULL,
  `Cargo` VARCHAR(45) NULL,
  `Melhor_filme` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Elenco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sertaoflix`.`elenco_filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`elenco_filme` (
  `Elenco_id_Elenco` INT NOT NULL,
  `filme_id_FIlme` INT NOT NULL,
  PRIMARY KEY (`Elenco_id_Elenco`, `filme_id_FIlme`),
  INDEX `fk_Elenco_has_filme_filme1_idx` (`filme_id_FIlme` ASC) VISIBLE,
  INDEX `fk_Elenco_has_filme_Elenco1_idx` (`Elenco_id_Elenco` ASC) VISIBLE,
  CONSTRAINT `fk_elenco_filme`
    FOREIGN KEY (`Elenco_id_Elenco`)
    REFERENCES `sertaoflix`.`elenco` (`id_Elenco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_lenco`
    FOREIGN KEY (`filme_id_FIlme`)
    REFERENCES `sertaoflix`.`filme` (`id_FIlme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sertaoflix`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`filme` (
  `id_FIlme` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(150) NULL DEFAULT NULL,
  `Sinopse` MEDIUMTEXT NULL DEFAULT NULL,
  `Duracao_min` INT NULL DEFAULT '0' COMMENT 'Duração em minutos\\n\\n',
  `data_lancamento` DATE NULL DEFAULT NULL,
  `Orcamento` DECIMAL(15,2) NULL DEFAULT '0.00',
  `Bilheteria` DECIMAL(15,2) NULL DEFAULT '0.00',
  `Lucro` DECIMAL(15,2) GENERATED ALWAYS AS ((`Bilheteria` - `Orcamento`)) VIRTUAL,
  `Poster_path` VARCHAR(255) NULL DEFAULT NULL, 
  `Nota_media` DECIMAL(3,1) NULL DEFAULT '0.0', 
  `Total_votos` INT NULL DEFAULT '0',
  `Classificacao_indicativa` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Livre, 10, 12, 14, 16, 18',
  `id_Elenco` INT NULL DEFAULT NULL,
  `sessao_id_Sessao` INT NOT NULL,
  PRIMARY KEY (`id_FIlme`),
  UNIQUE INDEX `id_FIlme_UNIQUE` (`id_FIlme` ASC) VISIBLE,
  INDEX `fk_filme_sessao1_idx` (`sessao_id_Sessao` ASC) VISIBLE,
  CONSTRAINT `fk_filme_sessao`
    FOREIGN KEY (`sessao_id_Sessao`)
    REFERENCES `sertaoflix`.`sessao` (`id_Sessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`funcionarios` (
  `id_Funcionarios` INT NOT NULL,
  `Nome` VARCHAR(150) NULL DEFAULT NULL,
  `Nascimento` DATE NULL DEFAULT NULL,
  `Funcao` VARCHAR(45) NULL DEFAULT NULL,
  `Cinema` VARCHAR(45) NULL DEFAULT NULL,
  `Genero` TINYINT NULL DEFAULT NULL,
  `Salario` INT NULL DEFAULT NULL,
  `cinema_id_Cinema` INT NOT NULL,
  PRIMARY KEY (`id_Funcionarios`),
  INDEX `fk_funcionarios_cinema1_idx` (`cinema_id_Cinema` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_cinema1`
    FOREIGN KEY (`cinema_id_Cinema`)
    REFERENCES `sertaoflix`.`cinema` (`id_Cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`genero` (
  `id_Genero` INT NOT NULL,
  `id_Filme` INT NOT NULL,
  `Genero` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`genero_filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`genero_filme` (
  `genero_id_Genero` INT NOT NULL,
  `filme_id_FIlme` INT NOT NULL,
  PRIMARY KEY (`genero_id_Genero`, `filme_id_FIlme`),
  INDEX `fk_genero_has_filme_filme1_idx` (`filme_id_FIlme` ASC) VISIBLE,
  INDEX `fk_genero_has_filme_genero1_idx` (`genero_id_Genero` ASC) VISIBLE,
  CONSTRAINT `fk_genero_filme`
    FOREIGN KEY (`genero_id_Genero`)
    REFERENCES `sertaoflix`.`genero` (`id_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_genero`
    FOREIGN KEY (`filme_id_FIlme`)
    REFERENCES `sertaoflix`.`filme` (`id_FIlme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`ingresso` (
  `id_Ingresso` INT NOT NULL,
  `Valor` INT NULL DEFAULT NULL,
  `Assento` VARCHAR(2) NULL,
  `Data_de_compra` DATETIME NULL DEFAULT NULL,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_sessao` INT NULL,
  `Tipo_Desconto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Ingresso`),
  INDEX `id_sessao_idx` (`id_sessao` ASC) VISIBLE,
  CONSTRAINT `fk_ingresso_sessao`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `sertaoflix`.`sessao` (`id_Sessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`ingresso_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`ingresso_cliente` (
  `ingresso_id_Ingresso` INT NOT NULL,
  `cliente_id_Cliente` INT NOT NULL,
  PRIMARY KEY (`ingresso_id_Ingresso`, `cliente_id_Cliente`),
  INDEX `fk_ingresso_has_cliente_cliente1_idx` (`cliente_id_Cliente` ASC) VISIBLE,
  INDEX `fk_ingresso_has_cliente_ingresso1_idx` (`ingresso_id_Ingresso` ASC) VISIBLE,
  CONSTRAINT `fk_ingresso__cliente`
    FOREIGN KEY (`ingresso_id_Ingresso`)
    REFERENCES `sertaoflix`.`ingresso` (`id_Ingresso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_ingresso`
    FOREIGN KEY (`cliente_id_Cliente`)
    REFERENCES `sertaoflix`.`cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`salas` (
  `id_Salas` INT NOT NULL,
  `Numero_Sala` INT NULL DEFAULT NULL,
  `Tipo` VARCHAR(45) NULL DEFAULT NULL,
  `Tamanho` INT NULL DEFAULT NULL,
  `Sistema_som` VARCHAR(45) NULL DEFAULT NULL,
  `Projecao` VARCHAR(45) NULL DEFAULT NULL,
  `Fileiras` INT NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `sessao_id_Sessao` INT NOT NULL,
  `cinema_id_Cinema` INT NOT NULL,
  PRIMARY KEY (`id_Salas`),
  INDEX `fk_salas_sessao1_idx` (`sessao_id_Sessao` ASC) VISIBLE,
  INDEX `fk_salas_cinema1_idx` (`cinema_id_Cinema` ASC) VISIBLE,
  CONSTRAINT `id_sessao`
    FOREIGN KEY (`sessao_id_Sessao`)
    REFERENCES `sertaoflix`.`sessao` (`id_Sessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salas_cinema1`
    FOREIGN KEY (`cinema_id_Cinema`)
    REFERENCES `sertaoflix`.`cinema` (`id_Cinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`sessao` (
  `id_Sessao` INT NOT NULL,
  `Duracao_da_sala` INT NULL DEFAULT NULL,
  `Horario` DATETIME NULL DEFAULT NULL,
  `Valor_Ingresso` TINYINT NULL DEFAULT NULL,
  `Desconto` TINYINT NULL DEFAULT NULL,
  `Rendimento_sessao` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Sessao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sertaoflix`.`log_salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`log_salas` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `id_sala` INT NOT NULL,
  `acao` VARCHAR(10) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `status_antigo` VARCHAR(45) NULL,
  `status_novo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sertaoflix`.`historico_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sertaoflix`.`historico_funcionarios` (
  `id_historico` INT NOT NULL AUTO_INCREMENT,
  `id_Funcionarios` INT NOT NULL,
  `Nome` VARCHAR(150) NULL,
  `Funcao` VARCHAR(45) NULL,
  `Salario` INT NULL,
  `data_desligamento` DATE NOT NULL,
  PRIMARY KEY (`id_historico`))
ENGINE = InnoDB;



ALTER TABLE elenco_filme 
RENAME COLUMN `filme_id_FIlme` TO `Filme_id_Filme`;
ALTER TABLE filme 
RENAME COLUMN data_lancamento TO Data_lancamento;
ALTER TABLE cliente DROP COLUMN `Saldo`;
ALTER TABLE sessao DROP COLUMN `Rendimento_sessao`;
ALTER TABLE cliente ADD `Total_ingresso` INT DEFAULT '0';




-- -----------------------------------------------------
-- DEFINIÇÃO DOS TRIGGERS
-- -----------------------------------------------------
DELIMITER $$

-- 1. TRIGGERS PARA A TABELA: avalia
CREATE TRIGGER `tg_valida_nota_insert` BEFORE INSERT ON `avalia`
FOR EACH ROW
BEGIN
    IF NEW.Nota IS NULL OR NEW.Nota < 1.0 OR NEW.Nota > 10.0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: A nota da avaliação deve estar entre 1 e 10.';
    END IF;
END$$

CREATE TRIGGER `tg_valida_nota_update` BEFORE UPDATE ON `avalia`
FOR EACH ROW
BEGIN
    IF NEW.Nota IS NULL OR NEW.Nota < 0.0 OR NEW.Nota > 10.0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: A nota da avaliação deve estar entre 0 e 10.';
    END IF;
END$$


-- 2. TRIGGERS PARA A TABELA: filme
CREATE TRIGGER `tg_valida_orcamento_insert` BEFORE INSERT ON `filme`
FOR EACH ROW
BEGIN
    IF NEW.Orcamento < 1.00 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: O orçamento do filme não pode ser menor que R$ 1,00.';
    END IF;
END$$

CREATE TRIGGER `tg_valida_orcamento_update` BEFORE UPDATE ON `filme`
FOR EACH ROW
BEGIN
    IF NEW.Orcamento < 1.00 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: O orçamento do filme não pode ser menor que R$ 1,00.';
    END IF;
END$$


-- 3. TRIGGERS PARA A TABELA: funcionarios
CREATE TRIGGER `tg_valida_salario_insert` BEFORE INSERT ON `funcionarios`
FOR EACH ROW
BEGIN
    IF NEW.Salario < 1650 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: O salário não pode ser menor que R$ 1.650,00.';
    END IF;
END$$

CREATE TRIGGER `tg_valida_salario_update` BEFORE UPDATE ON `funcionarios`
FOR EACH ROW
BEGIN
    IF NEW.Salario < 1650 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: O salário não pode ser menor que R$ 1.650,00.';
    END IF;
END$$



CREATE TRIGGER `tg_historico_demissao` AFTER DELETE ON `funcionarios`
FOR EACH ROW
BEGIN
    INSERT INTO sertaoflix.historico_funcionarios (id_Funcionarios, Nome, Funcao, Salario, data_desligamento)
    VALUES (OLD.id_Funcionarios, OLD.Nome, OLD.Funcao, OLD.Salario, CURDATE());
END$$


-- 4. TRIGGERS PARA A TABELA: salas
CREATE TRIGGER `tg_auditoria_salas_update` AFTER UPDATE ON `salas`
FOR EACH ROW
BEGIN
    IF OLD.Status <> NEW.Status OR OLD.Tipo <> NEW.Tipo THEN
        INSERT INTO sertaoflix.log_salas (id_sala, acao, usuario, data_hora, status_antigo, status_novo)
        VALUES (OLD.id_Salas, 'UPDATE', USER(), NOW(), OLD.Status, NEW.Status);
    END IF;
END$$


-- 5. TRIGGERS PARA A TABELA: ingresso
CREATE TRIGGER `tg_valida_ingresso_sessao_passada` BEFORE INSERT ON `ingresso`
FOR EACH ROW
BEGIN
    DECLARE v_horario DATETIME;
    SELECT Horario INTO v_horario FROM sertaoflix.sessao WHERE id_Sessao = NEW.id_sessao;
    
    IF v_horario < NOW() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: Sessão encerrada. Venda de ingressos indisponível.';
    END IF;
    
    IF EXISTS (SELECT 1 FROM sertaoflix.ingresso WHERE id_sessao = NEW.id_sessao AND Assento = NEW.Assento) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erro: O assento selecionado já está ocupado nesta sessão.';
    END IF;
END$$


-- 6. TRIGGERS PARA A TABELA: ingresso_cliente

DELIMITER $$

-- Trigger principal que roda a cada novo ingresso vinculado ao cliente
CREATE TRIGGER `tg_atualiza_fidelidade_temporal` AFTER INSERT ON `ingresso_cliente`
FOR EACH ROW
BEGIN
    DECLARE v_ingressos_ano INT;
    DECLARE v_status_atual VARCHAR(10);
    DECLARE v_data_prata DATETIME;

    -- 1. Recupera o status atual do cliente e a data em que ele virou Prata
    SELECT `Nivel_fidelidade`, `Data_Virou_Prata` 
    INTO v_status_atual, v_data_prata
    FROM sertaoflix.cliente 
    WHERE `id_Cliente` = NEW.cliente_id_Cliente;

    -- 2. Conta quantos ingressos o cliente comprou nos últimos 365 dias (1 ano)
    SELECT COUNT(DISTINCT ic.ingresso_id_Ingresso) INTO v_ingressos_ano
    FROM sertaoflix.ingresso_cliente ic
    JOIN sertaoflix.ingresso i ON ic.ingresso_id_Ingresso = i.id_Ingresso
    WHERE ic.cliente_id_Cliente = NEW.cliente_id_Cliente
      AND i.Data_de_compra >= DATE_SUB(NOW(), INTERVAL 1 YEAR);

    -- 3. Aplica as regras de negócio para Upgrade
    IF v_ingressos_ano > 30 AND v_status_atual = 'Prata' AND v_data_prata <= DATE_SUB(NOW(), INTERVAL 1 MONTH) THEN
        -- Vira Ouro apenas se tiver mais de 30 no ano E se passou 1 mês desde que virou Prata
        UPDATE sertaoflix.cliente 
        SET `Nivel_fidelidade` = 'Ouro' 
        WHERE `id_Cliente` = NEW.cliente_id_Cliente;
        
    ELSEIF v_ingressos_ano > 20 AND v_status_atual = 'Bronze' THEN
        -- Vira Prata se tiver mais de 20 no ano. Grava o momento exato do upgrade.
        UPDATE sertaoflix.cliente 
        SET `Nivel_fidelidade` = 'Prata', 
            `Data_Virou_Prata` = NOW() 
        WHERE `id_Cliente` = NEW.cliente_id_Cliente;
    END IF;
END$$

-- Trigger para o caso de downgrade (se passar o tempo e os ingressos do ano expirarem)
CREATE TRIGGER `tg_reavalia_fidelidade_delete` AFTER DELETE ON `ingresso_cliente`
FOR EACH ROW
BEGIN
    DECLARE v_ingressos_ano INT;
    DECLARE v_status_atual VARCHAR(10);

    SELECT `Nivel_fidelidade` INTO v_status_atual
    FROM sertaoflix.cliente 
    WHERE `id_Cliente` = OLD.cliente_id_Cliente;

    SELECT COUNT(DISTINCT ic.ingresso_id_Ingresso) INTO v_ingressos_ano
    FROM sertaoflix.ingresso_cliente ic
    JOIN sertaoflix.ingresso i ON ic.ingresso_id_Ingresso = i.id_Ingresso
    WHERE ic.cliente_id_Cliente = OLD.cliente_id_Cliente
      AND i.Data_de_compra >= DATE_SUB(NOW(), INTERVAL 1 YEAR);

    -- Regra de rebaixamento caso ingressos sejam estornados/deletados
    IF v_ingressos_ano <= 20 AND v_status_atual <> 'Bronze' THEN
        UPDATE sertaoflix.cliente 
        SET `Nivel_fidelidade` = 'Bronze', `Data_Virou_Prata` = NULL 
        WHERE `id_Cliente` = OLD.cliente_id_Cliente;
    ELSEIF v_ingressos_ano <= 30 AND v_status_atual = 'Ouro' THEN
        UPDATE sertaoflix.cliente 
        SET `Nivel_fidelidade` = 'Prata' 
        WHERE `id_Cliente` = OLD.cliente_id_Cliente;
    END IF;
END$$


CREATE TRIGGER `tg_incrementa_total_ingressos` AFTER INSERT ON `ingresso_cliente`
FOR EACH ROW
BEGIN
    UPDATE sertaoflix.cliente 
    SET Total_ingresso = Total_ingresso + 1
    WHERE id_Cliente = NEW.cliente_id_Cliente;
END$$

CREATE TRIGGER `tg_decrementa_total_ingressos` AFTER DELETE ON `ingresso_cliente`
FOR EACH ROW
BEGIN
    UPDATE sertaoflix.cliente 
    SET Total_ingresso = GREATEST(0, Total_ingresso - 1)
    WHERE id_Cliente = OLD.cliente_id_Cliente;
END$$

DELIMITER ;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
	